### ISSUE TITLE
use python3 have Question

### ISSUE THREAD

**Issue by kmolLin** [ethanlu/pazudora-solver#1]
![image](https://cloud.githubusercontent.com/assets/8325379/22595974/94358d12-ea64-11e6-91ec-ad6c71a32d5a.png)

May I ask Question to do the correct the Question and use the python3 to use the solver ?

**Comment by ethanlu** [comment]
Ah, I haven't upgraded this code to support Python 3.x yet. Will work on getting Python 3 support in the new couple of days.

**Comment by ethanlu** [comment]
upgraded to python 3.4. version 0.2.0 would have this change.
